const countries = [
  {
    common: "Aruba",
    official: "Aruba",
    native: { official: "Aruba", common: "Aruba" },
    cca2: "AW",
  },
  {
    common: "Afghanistan",
    official: "Islamic Republic of Afghanistan",
    native: { official: "جمهوری اسلامی افغانستان", common: "افغانستان" },
    cca2: "AF",
  },
  {
    common: "Angola",
    official: "Republic of Angola",
    native: { official: "República de Angola", common: "Angola" },
    cca2: "AO",
  },
  {
    common: "Anguilla",
    official: "Anguilla",
    native: { official: "Anguilla", common: "Anguilla" },
    cca2: "AI",
  },
  {
    common: "Åland Islands",
    official: "Åland Islands",
    native: { official: "Landskapet Åland", common: "Åland" },
    cca2: "AX",
  },
  {
    common: "Albania",
    official: "Republic of Albania",
    native: { official: "Republika e Shqipërisë", common: "Shqipëria" },
    cca2: "AL",
  },
  {
    common: "Andorra",
    official: "Principality of Andorra",
    native: { official: "Principat d'Andorra", common: "Andorra" },
    cca2: "AD",
  },
  {
    common: "United Arab Emirates",
    official: "United Arab Emirates",
    native: {
      official: "الإمارات العربية المتحدة",
      common: "دولة الإمارات العربية المتحدة",
    },
    cca2: "AE",
  },
  {
    common: "Argentina",
    official: "Argentine Republic",
    native: { official: "Argentine Republic", common: "Argentina" },
    cca2: "AR",
  },
  {
    common: "Armenia",
    official: "Republic of Armenia",
    native: { official: "Հայաստանի Հանրապետություն", common: "Հայաստան" },
    cca2: "AM",
  },
  {
    common: "American Samoa",
    official: "American Samoa",
    native: { official: "American Samoa", common: "American Samoa" },
    cca2: "AS",
  },
  { common: "Antarctica", official: "Antarctica", cca2: "AQ" },
  {
    common: "French Southern and Antarctic Lands",
    official: "Territory of the French Southern and Antarctic Lands",
    native: {
      official: "Territoire des Terres australes et antarctiques françaises",
      common: "Terres australes et antarctiques françaises",
    },
    cca2: "TF",
  },
  {
    common: "Antigua and Barbuda",
    official: "Antigua and Barbuda",
    native: { official: "Antigua and Barbuda", common: "Antigua and Barbuda" },
    cca2: "AG",
  },
  {
    common: "Australia",
    official: "Commonwealth of Australia",
    native: { official: "Commonwealth of Australia", common: "Australia" },
    cca2: "AU",
  },
  {
    common: "Austria",
    official: "Republic of Austria",
    native: { official: "Republik Österreich", common: "Österreich" },
    cca2: "AT",
  },
  {
    common: "Azerbaijan",
    official: "Republic of Azerbaijan",
    native: { official: "Azərbaycan Respublikası", common: "Azərbaycan" },
    cca2: "AZ",
  },
  {
    common: "Burundi",
    official: "Republic of Burundi",
    native: { official: "République du Burundi", common: "Burundi" },
    cca2: "BI",
  },
  {
    common: "Belgium",
    official: "Kingdom of Belgium",
    native: { official: "Königreich Belgien", common: "Belgien" },
    cca2: "BE",
  },
  {
    common: "Benin",
    official: "Republic of Benin",
    native: { official: "République du Bénin", common: "Bénin" },
    cca2: "BJ",
  },
  {
    common: "Burkina Faso",
    official: "Burkina Faso",
    native: { official: "République du Burkina", common: "Burkina Faso" },
    cca2: "BF",
  },
  {
    common: "Bangladesh",
    official: "People's Republic of Bangladesh",
    native: { official: "বাংলাদেশ গণপ্রজাতন্ত্রী", common: "বাংলাদেশ" },
    cca2: "BD",
  },
  {
    common: "Bulgaria",
    official: "Republic of Bulgaria",
    native: { official: "Република България", common: "България" },
    cca2: "BG",
  },
  {
    common: "Bahrain",
    official: "Kingdom of Bahrain",
    native: { official: "مملكة البحرين", common: "‏البحرين" },
    cca2: "BH",
  },
  {
    common: "Bahamas",
    official: "Commonwealth of the Bahamas",
    native: { official: "Commonwealth of the Bahamas", common: "Bahamas" },
    cca2: "BS",
  },
  {
    common: "Bosnia and Herzegovina",
    official: "Bosnia and Herzegovina",
    native: { official: "Bosna i Hercegovina", common: "Bosna i Hercegovina" },
    cca2: "BA",
  },
  {
    common: "Saint Barthélemy",
    official: "Collectivity of Saint Barthélemy",
    native: {
      official: "Collectivité de Saint-Barthélemy",
      common: "Saint-Barthélemy",
    },
    cca2: "BL",
  },
  {
    common: "Saint Helena, Ascension and Tristan da Cunha",
    official: "Saint Helena, Ascension and Tristan da Cunha",
    native: {
      official: "Saint Helena, Ascension and Tristan da Cunha",
      common: "Saint Helena, Ascension and Tristan da Cunha",
    },
    cca2: "SH",
  },
  {
    common: "Belarus",
    official: "Republic of Belarus",
    native: { official: "Рэспубліка Беларусь", common: "Белару́сь" },
    cca2: "BY",
  },
  {
    common: "Belize",
    official: "Belize",
    native: { official: "Belize", common: "Belize" },
    cca2: "BZ",
  },
  {
    common: "Bermuda",
    official: "Bermuda",
    native: { official: "Bermuda", common: "Bermuda" },
    cca2: "BM",
  },
  {
    common: "Bolivia",
    official: "Plurinational State of Bolivia",
    native: { official: "Wuliwya Suyu", common: "Wuliwya" },
    cca2: "BO",
  },
  {
    common: "Caribbean Netherlands",
    official: "Bonaire, Sint Eustatius and Saba",
    native: {
      official: "Bonaire, Sint Eustatius en Saba",
      common: "Caribisch Nederland",
    },
    cca2: "BQ",
  },
  {
    common: "Brazil",
    official: "Federative Republic of Brazil",
    native: { official: "República Federativa do Brasil", common: "Brasil" },
    cca2: "BR",
  },
  {
    common: "Barbados",
    official: "Barbados",
    native: { official: "Barbados", common: "Barbados" },
    cca2: "BB",
  },
  {
    common: "Brunei",
    official: "Nation of Brunei, Abode of Peace",
    native: {
      official: "Nation of Brunei, Abode Damai",
      common: "Negara Brunei Darussalam",
    },
    cca2: "BN",
  },
  {
    common: "Bhutan",
    official: "Kingdom of Bhutan",
    native: { official: "འབྲུག་རྒྱལ་ཁབ་", common: "འབྲུག་ཡུལ་" },
    cca2: "BT",
  },
  {
    common: "Bouvet Island",
    official: "Bouvet Island",
    native: { official: "Bouvetøya", common: "Bouvetøya" },
    cca2: "BV",
  },
  {
    common: "Botswana",
    official: "Republic of Botswana",
    native: { official: "Republic of Botswana", common: "Botswana" },
    cca2: "BW",
  },
  {
    common: "Central African Republic",
    official: "Central African Republic",
    native: {
      official: "République centrafricaine",
      common: "République centrafricaine",
    },
    cca2: "CF",
  },
  {
    common: "Canada",
    official: "Canada",
    native: { official: "Canada", common: "Canada" },
    cca2: "CA",
  },
  {
    common: "Cocos (Keeling) Islands",
    official: "Territory of the Cocos (Keeling) Islands",
    native: {
      official: "Territory of the Cocos (Keeling) Islands",
      common: "Cocos (Keeling) Islands",
    },
    cca2: "CC",
  },
  {
    common: "Switzerland",
    official: "Swiss Confederation",
    native: { official: "Confédération suisse", common: "Suisse" },
    cca2: "CH",
  },
  {
    common: "Chile",
    official: "Republic of Chile",
    native: { official: "República de Chile", common: "Chile" },
    cca2: "CL",
  },
  {
    common: "China",
    official: "People's Republic of China",
    native: { official: "中华人民共和国", common: "中国" },
    cca2: "CN",
  },
  {
    common: "Ivory Coast",
    official: "Republic of Côte d'Ivoire",
    native: {
      official: "République de Côte d'Ivoire",
      common: "Côte d'Ivoire",
    },
    cca2: "CI",
  },
  {
    common: "Cameroon",
    official: "Republic of Cameroon",
    native: { official: "Republic of Cameroon", common: "Cameroon" },
    cca2: "CM",
  },
  {
    common: "DR Congo",
    official: "Democratic Republic of the Congo",
    native: {
      official: "République démocratique du Congo",
      common: "RD Congo",
    },
    cca2: "CD",
  },
  {
    common: "Republic of the Congo",
    official: "Republic of the Congo",
    native: { official: "République du Congo", common: "République du Congo" },
    cca2: "CG",
  },
  {
    common: "Cook Islands",
    official: "Cook Islands",
    native: { official: "Cook Islands", common: "Cook Islands" },
    cca2: "CK",
  },
  {
    common: "Colombia",
    official: "Republic of Colombia",
    native: { official: "República de Colombia", common: "Colombia" },
    cca2: "CO",
  },
  {
    common: "Comoros",
    official: "Union of the Comoros",
    native: { official: "الاتحاد القمري", common: "القمر‎" },
    cca2: "KM",
  },
  {
    common: "Cape Verde",
    official: "Republic of Cabo Verde",
    native: { official: "República de Cabo Verde", common: "Cabo Verde" },
    cca2: "CV",
  },
  {
    common: "Costa Rica",
    official: "Republic of Costa Rica",
    native: { official: "República de Costa Rica", common: "Costa Rica" },
    cca2: "CR",
  },
  {
    common: "Cuba",
    official: "Republic of Cuba",
    native: { official: "República de Cuba", common: "Cuba" },
    cca2: "CU",
  },
  {
    common: "Curaçao",
    official: "Country of Curaçao",
    native: { official: "Country of Curaçao", common: "Curaçao" },
    cca2: "CW",
  },
  {
    common: "Christmas Island",
    official: "Territory of Christmas Island",
    native: {
      official: "Territory of Christmas Island",
      common: "Christmas Island",
    },
    cca2: "CX",
  },
  {
    common: "Cayman Islands",
    official: "Cayman Islands",
    native: { official: "Cayman Islands", common: "Cayman Islands" },
    cca2: "KY",
  },
  {
    common: "Cyprus",
    official: "Republic of Cyprus",
    native: { official: "Δημοκρατία της Κύπρος", common: "Κύπρος" },
    cca2: "CY",
  },
  {
    common: "Czechia",
    official: "Czech Republic",
    native: { official: "Česká republika", common: "Česko" },
    cca2: "CZ",
  },
  {
    common: "Germany",
    official: "Federal Republic of Germany",
    native: { official: "Bundesrepublik Deutschland", common: "Deutschland" },
    cca2: "DE",
  },
  {
    common: "Djibouti",
    official: "Republic of Djibouti",
    native: { official: "جمهورية جيبوتي", common: "جيبوتي‎" },
    cca2: "DJ",
  },
  {
    common: "Dominica",
    official: "Commonwealth of Dominica",
    native: { official: "Commonwealth of Dominica", common: "Dominica" },
    cca2: "DM",
  },
  {
    common: "Denmark",
    official: "Kingdom of Denmark",
    native: { official: "Kongeriget Danmark", common: "Danmark" },
    cca2: "DK",
  },
  {
    common: "Dominican Republic",
    official: "Dominican Republic",
    native: {
      official: "República Dominicana",
      common: "República Dominicana",
    },
    cca2: "DO",
  },
  {
    common: "Algeria",
    official: "People's Democratic Republic of Algeria",
    native: {
      official: "الجمهورية الديمقراطية الشعبية الجزائرية",
      common: "الجزائر",
    },
    cca2: "DZ",
  },
  {
    common: "Ecuador",
    official: "Republic of Ecuador",
    native: { official: "República del Ecuador", common: "Ecuador" },
    cca2: "EC",
  },
  {
    common: "Egypt",
    official: "Arab Republic of Egypt",
    native: { official: "جمهورية مصر العربية", common: "مصر" },
    cca2: "EG",
  },
  {
    common: "Eritrea",
    official: "State of Eritrea",
    native: { official: "دولة إرتريا", common: "إرتريا‎" },
    cca2: "ER",
  },
  {
    common: "Western Sahara",
    official: "Sahrawi Arab Democratic Republic",
    native: {
      official: "Sahrawi Arab Democratic Republic",
      common: "Western Sahara",
    },
    cca2: "EH",
  },
  {
    common: "Spain",
    official: "Kingdom of Spain",
    native: { official: "Reino de España", common: "España" },
    cca2: "ES",
  },
  {
    common: "Estonia",
    official: "Republic of Estonia",
    native: { official: "Eesti Vabariik", common: "Eesti" },
    cca2: "EE",
  },
  {
    common: "Ethiopia",
    official: "Federal Democratic Republic of Ethiopia",
    native: { official: "የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ", common: "ኢትዮጵያ" },
    cca2: "ET",
  },
  {
    common: "Finland",
    official: "Republic of Finland",
    native: { official: "Suomen tasavalta", common: "Suomi" },
    cca2: "FI",
  },
  {
    common: "Fiji",
    official: "Republic of Fiji",
    native: { official: "Republic of Fiji", common: "Fiji" },
    cca2: "FJ",
  },
  {
    common: "Falkland Islands",
    official: "Falkland Islands",
    native: { official: "Falkland Islands", common: "Falkland Islands" },
    cca2: "FK",
  },
  {
    common: "France",
    official: "French Republic",
    native: { official: "République française", common: "France" },
    cca2: "FR",
  },
  {
    common: "Faroe Islands",
    official: "Faroe Islands",
    native: { official: "Færøerne", common: "Færøerne" },
    cca2: "FO",
  },
  {
    common: "Micronesia",
    official: "Federated States of Micronesia",
    native: {
      official: "Federated States of Micronesia",
      common: "Micronesia",
    },
    cca2: "FM",
  },
  {
    common: "Gabon",
    official: "Gabonese Republic",
    native: { official: "République gabonaise", common: "Gabon" },
    cca2: "GA",
  },
  {
    common: "United Kingdom",
    official: "United Kingdom of Great Britain and Northern Ireland",
    native: {
      official: "United Kingdom of Great Britain and Northern Ireland",
      common: "United Kingdom",
    },
    cca2: "GB",
  },
  {
    common: "Georgia",
    official: "Georgia",
    native: { official: "საქართველო", common: "საქართველო" },
    cca2: "GE",
  },
  {
    common: "Guernsey",
    official: "Bailiwick of Guernsey",
    native: { official: "Bailiwick of Guernsey", common: "Guernsey" },
    cca2: "GG",
  },
  {
    common: "Ghana",
    official: "Republic of Ghana",
    native: { official: "Republic of Ghana", common: "Ghana" },
    cca2: "GH",
  },
  {
    common: "Gibraltar",
    official: "Gibraltar",
    native: { official: "Gibraltar", common: "Gibraltar" },
    cca2: "GI",
  },
  {
    common: "Guinea",
    official: "Republic of Guinea",
    native: { official: "République de Guinée", common: "Guinée" },
    cca2: "GN",
  },
  {
    common: "Guadeloupe",
    official: "Guadeloupe",
    native: { official: "Guadeloupe", common: "Guadeloupe" },
    cca2: "GP",
  },
  {
    common: "Gambia",
    official: "Republic of the Gambia",
    native: { official: "Republic of the Gambia", common: "Gambia" },
    cca2: "GM",
  },
  {
    common: "Guinea-Bissau",
    official: "Republic of Guinea-Bissau",
    native: { official: "República da Guiné-Bissau", common: "Guiné-Bissau" },
    cca2: "GW",
  },
  {
    common: "Equatorial Guinea",
    official: "Republic of Equatorial Guinea",
    native: {
      official: "République de la Guinée Équatoriale",
      common: "Guinée équatoriale",
    },
    cca2: "GQ",
  },
  {
    common: "Greece",
    official: "Hellenic Republic",
    native: { official: "Ελληνική Δημοκρατία", common: "Ελλάδα" },
    cca2: "GR",
  },
  {
    common: "Grenada",
    official: "Grenada",
    native: { official: "Grenada", common: "Grenada" },
    cca2: "GD",
  },
  {
    common: "Greenland",
    official: "Greenland",
    native: { official: "Kalaallit Nunaat", common: "Kalaallit Nunaat" },
    cca2: "GL",
  },
  {
    common: "Guatemala",
    official: "Republic of Guatemala",
    native: { official: "República de Guatemala", common: "Guatemala" },
    cca2: "GT",
  },
  {
    common: "French Guiana",
    official: "Guiana",
    native: { official: "Guyane", common: "Guyane française" },
    cca2: "GF",
  },
  {
    common: "Guam",
    official: "Guam",
    native: { official: "Guåhån", common: "Guåhån" },
    cca2: "GU",
  },
  {
    common: "Guyana",
    official: "Co-operative Republic of Guyana",
    native: { official: "Co-operative Republic of Guyana", common: "Guyana" },
    cca2: "GY",
  },
  {
    common: "Hong Kong",
    official:
      "Hong Kong Special Administrative Region of the People's Republic of China",
    native: {
      official:
        "Hong Kong Special Administrative Region of the People's Republic of China",
      common: "Hong Kong",
    },
    cca2: "HK",
  },
  {
    common: "Heard Island and McDonald Islands",
    official: "Heard Island and McDonald Islands",
    native: {
      official: "Heard Island and McDonald Islands",
      common: "Heard Island and McDonald Islands",
    },
    cca2: "HM",
  },
  {
    common: "Honduras",
    official: "Republic of Honduras",
    native: { official: "República de Honduras", common: "Honduras" },
    cca2: "HN",
  },
  {
    common: "Croatia",
    official: "Republic of Croatia",
    native: { official: "Republika Hrvatska", common: "Hrvatska" },
    cca2: "HR",
  },
  {
    common: "Haiti",
    official: "Republic of Haiti",
    native: { official: "République d'Haïti", common: "Haïti" },
    cca2: "HT",
  },
  {
    common: "Hungary",
    official: "Hungary",
    native: { official: "Magyarország", common: "Magyarország" },
    cca2: "HU",
  },
  {
    common: "Indonesia",
    official: "Republic of Indonesia",
    native: { official: "Republik Indonesia", common: "Indonesia" },
    cca2: "ID",
  },
  {
    common: "Isle of Man",
    official: "Isle of Man",
    native: { official: "Isle of Man", common: "Isle of Man" },
    cca2: "IM",
  },
  {
    common: "India",
    official: "Republic of India",
    native: { official: "Republic of India", common: "India" },
    cca2: "IN",
  },
  {
    common: "British Indian Ocean Territory",
    official: "British Indian Ocean Territory",
    native: {
      official: "British Indian Ocean Territory",
      common: "British Indian Ocean Territory",
    },
    cca2: "IO",
  },
  {
    common: "Ireland",
    official: "Republic of Ireland",
    native: { official: "Republic of Ireland", common: "Ireland" },
    cca2: "IE",
  },
  {
    common: "Iran",
    official: "Islamic Republic of Iran",
    native: { official: "جمهوری اسلامی ایران", common: "ایران" },
    cca2: "IR",
  },
  {
    common: "Iraq",
    official: "Republic of Iraq",
    native: { official: "جمهورية العراق", common: "العراق" },
    cca2: "IQ",
  },
  {
    common: "Iceland",
    official: "Iceland",
    native: { official: "Ísland", common: "Ísland" },
    cca2: "IS",
  },
  {
    common: "Israel",
    official: "State of Israel",
    native: { official: "دولة إسرائيل", common: "إسرائيل" },
    cca2: "IL",
  },
  {
    common: "Italy",
    official: "Italian Republic",
    native: { official: "Repubblica italiana", common: "Italia" },
    cca2: "IT",
  },
  {
    common: "Jamaica",
    official: "Jamaica",
    native: { official: "Jamaica", common: "Jamaica" },
    cca2: "JM",
  },
  {
    common: "Jersey",
    official: "Bailiwick of Jersey",
    native: { official: "Bailiwick of Jersey", common: "Jersey" },
    cca2: "JE",
  },
  {
    common: "Jordan",
    official: "Hashemite Kingdom of Jordan",
    native: { official: "المملكة الأردنية الهاشمية", common: "الأردن" },
    cca2: "JO",
  },
  {
    common: "Japan",
    official: "Japan",
    native: { official: "日本", common: "日本" },
    cca2: "JP",
  },
  {
    common: "Kazakhstan",
    official: "Republic of Kazakhstan",
    native: { official: "Қазақстан Республикасы", common: "Қазақстан" },
    cca2: "KZ",
  },
  {
    common: "Kenya",
    official: "Republic of Kenya",
    native: { official: "Republic of Kenya", common: "Kenya" },
    cca2: "KE",
  },
  {
    common: "Kyrgyzstan",
    official: "Kyrgyz Republic",
    native: { official: "Кыргыз Республикасы", common: "Кыргызстан" },
    cca2: "KG",
  },
  {
    common: "Cambodia",
    official: "Kingdom of Cambodia",
    native: { official: "ព្រះរាជាណាចក្រកម្ពុជា", common: "Kâmpŭchéa" },
    cca2: "KH",
  },
  {
    common: "Kiribati",
    official: "Independent and Sovereign Republic of Kiribati",
    native: {
      official: "Independent and Sovereign Republic of Kiribati",
      common: "Kiribati",
    },
    cca2: "KI",
  },
  {
    common: "Saint Kitts and Nevis",
    official: "Federation of Saint Christopher and Nevis",
    native: {
      official: "Federation of Saint Christopher and Nevis",
      common: "Saint Kitts and Nevis",
    },
    cca2: "KN",
  },
  {
    common: "South Korea",
    official: "Republic of Korea",
    native: { official: "대한민국", common: "한국" },
    cca2: "KR",
  },
  {
    common: "Kosovo",
    official: "Republic of Kosovo",
    native: { official: "Republika e Kosovës", common: "Kosova" },
    cca2: "XK",
  },
  {
    common: "Kuwait",
    official: "State of Kuwait",
    native: { official: "دولة الكويت", common: "الكويت" },
    cca2: "KW",
  },
  {
    common: "Laos",
    official: "Lao People's Democratic Republic",
    native: { official: "ສາທາລະນະ ຊາທິປະໄຕ ຄົນລາວ ຂອງ", common: "ສປປລາວ" },
    cca2: "LA",
  },
  {
    common: "Lebanon",
    official: "Lebanese Republic",
    native: { official: "الجمهورية اللبنانية", common: "لبنان" },
    cca2: "LB",
  },
  {
    common: "Liberia",
    official: "Republic of Liberia",
    native: { official: "Republic of Liberia", common: "Liberia" },
    cca2: "LR",
  },
  {
    common: "Libya",
    official: "State of Libya",
    native: { official: "الدولة ليبيا", common: "‏ليبيا" },
    cca2: "LY",
  },
  {
    common: "Saint Lucia",
    official: "Saint Lucia",
    native: { official: "Saint Lucia", common: "Saint Lucia" },
    cca2: "LC",
  },
  {
    common: "Liechtenstein",
    official: "Principality of Liechtenstein",
    native: { official: "Fürstentum Liechtenstein", common: "Liechtenstein" },
    cca2: "LI",
  },
  {
    common: "Sri Lanka",
    official: "Democratic Socialist Republic of Sri Lanka",
    native: {
      official: "ශ්‍රී ලංකා ප්‍රජාතාන්ත්‍රික සමාජවාදී ජනරජය",
      common: "ශ්‍රී ලංකාව",
    },
    cca2: "LK",
  },
  {
    common: "Lesotho",
    official: "Kingdom of Lesotho",
    native: { official: "Kingdom of Lesotho", common: "Lesotho" },
    cca2: "LS",
  },
  {
    common: "Lithuania",
    official: "Republic of Lithuania",
    native: { official: "Lietuvos Respublikos", common: "Lietuva" },
    cca2: "LT",
  },
  {
    common: "Luxembourg",
    official: "Grand Duchy of Luxembourg",
    native: { official: "Großherzogtum Luxemburg", common: "Luxemburg" },
    cca2: "LU",
  },
  {
    common: "Latvia",
    official: "Republic of Latvia",
    native: { official: "Latvijas Republikas", common: "Latvija" },
    cca2: "LV",
  },
  {
    common: "Macau",
    official:
      "Macao Special Administrative Region of the People's Republic of China",
    native: {
      official:
        "Região Administrativa Especial de Macau da República Popular da China",
      common: "Macau",
    },
    cca2: "MO",
  },
  {
    common: "Saint Martin",
    official: "Saint Martin",
    native: { official: "Saint-Martin", common: "Saint-Martin" },
    cca2: "MF",
  },
  {
    common: "Morocco",
    official: "Kingdom of Morocco",
    native: { official: "المملكة المغربية", common: "المغرب" },
    cca2: "MA",
  },
  {
    common: "Monaco",
    official: "Principality of Monaco",
    native: { official: "Principauté de Monaco", common: "Monaco" },
    cca2: "MC",
  },
  {
    common: "Moldova",
    official: "Republic of Moldova",
    native: { official: "Republica Moldova", common: "Moldova" },
    cca2: "MD",
  },
  {
    common: "Madagascar",
    official: "Republic of Madagascar",
    native: { official: "République de Madagascar", common: "Madagascar" },
    cca2: "MG",
  },
  {
    common: "Maldives",
    official: "Republic of the Maldives",
    native: {
      official: "ދިވެހިރާއްޖޭގެ ޖުމްހޫރިއްޔާ",
      common: "ދިވެހިރާއްޖޭގެ",
    },
    cca2: "MV",
  },
  {
    common: "Mexico",
    official: "United Mexican States",
    native: { official: "Estados Unidos Mexicanos", common: "México" },
    cca2: "MX",
  },
  {
    common: "Marshall Islands",
    official: "Republic of the Marshall Islands",
    native: {
      official: "Republic of the Marshall Islands",
      common: "Marshall Islands",
    },
    cca2: "MH",
  },
  {
    common: "North Macedonia",
    official: "Republic of North Macedonia",
    native: { official: "Република Северна Македонија", common: "Македонија" },
    cca2: "MK",
  },
  {
    common: "Mali",
    official: "Republic of Mali",
    native: { official: "République du Mali", common: "Mali" },
    cca2: "ML",
  },
  {
    common: "Malta",
    official: "Republic of Malta",
    native: { official: "Republic of Malta", common: "Malta" },
    cca2: "MT",
  },
  {
    common: "Myanmar",
    official: "Republic of the Union of Myanmar",
    native: {
      official: "ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်",
      common: "မြန်မာ",
    },
    cca2: "MM",
  },
  {
    common: "Montenegro",
    official: "Montenegro",
    native: { official: "Црна Гора", common: "Црна Гора" },
    cca2: "ME",
  },
  {
    common: "Mongolia",
    official: "Mongolia",
    native: { official: "Монгол улс", common: "Монгол улс" },
    cca2: "MN",
  },
  {
    common: "Northern Mariana Islands",
    official: "Commonwealth of the Northern Mariana Islands",
    native: {
      official: "Commonwealth of the Northern Mariana Islands",
      common: "Northern Mariana Islands",
    },
    cca2: "MP",
  },
  {
    common: "Mozambique",
    official: "Republic of Mozambique",
    native: { official: "República de Moçambique", common: "Moçambique" },
    cca2: "MZ",
  },
  {
    common: "Mauritania",
    official: "Islamic Republic of Mauritania",
    native: {
      official: "الجمهورية الإسلامية الموريتانية",
      common: "موريتانيا",
    },
    cca2: "MR",
  },
  {
    common: "Montserrat",
    official: "Montserrat",
    native: { official: "Montserrat", common: "Montserrat" },
    cca2: "MS",
  },
  {
    common: "Martinique",
    official: "Martinique",
    native: { official: "Martinique", common: "Martinique" },
    cca2: "MQ",
  },
  {
    common: "Mauritius",
    official: "Republic of Mauritius",
    native: { official: "Republic of Mauritius", common: "Mauritius" },
    cca2: "MU",
  },
  {
    common: "Malawi",
    official: "Republic of Malawi",
    native: { official: "Republic of Malawi", common: "Malawi" },
    cca2: "MW",
  },
  {
    common: "Malaysia",
    official: "Malaysia",
    native: { official: "Malaysia", common: "Malaysia" },
    cca2: "MY",
  },
  {
    common: "Mayotte",
    official: "Department of Mayotte",
    native: { official: "Département de Mayotte", common: "Mayotte" },
    cca2: "YT",
  },
  {
    common: "Namibia",
    official: "Republic of Namibia",
    native: { official: "Republiek van Namibië", common: "Namibië" },
    cca2: "NA",
  },
  {
    common: "New Caledonia",
    official: "New Caledonia",
    native: { official: "Nouvelle-Calédonie", common: "Nouvelle-Calédonie" },
    cca2: "NC",
  },
  {
    common: "Niger",
    official: "Republic of Niger",
    native: { official: "République du Niger", common: "Niger" },
    cca2: "NE",
  },
  {
    common: "Norfolk Island",
    official: "Territory of Norfolk Island",
    native: {
      official: "Territory of Norfolk Island",
      common: "Norfolk Island",
    },
    cca2: "NF",
  },
  {
    common: "Nigeria",
    official: "Federal Republic of Nigeria",
    native: { official: "Federal Republic of Nigeria", common: "Nigeria" },
    cca2: "NG",
  },
  {
    common: "Nicaragua",
    official: "Republic of Nicaragua",
    native: { official: "República de Nicaragua", common: "Nicaragua" },
    cca2: "NI",
  },
  {
    common: "Niue",
    official: "Niue",
    native: { official: "Niue", common: "Niue" },
    cca2: "NU",
  },
  {
    common: "Netherlands",
    official: "Kingdom of the Netherlands",
    native: { official: "Koninkrijk der Nederlanden", common: "Nederland" },
    cca2: "NL",
  },
  {
    common: "Norway",
    official: "Kingdom of Norway",
    native: { official: "Kongeriket Noreg", common: "Noreg" },
    cca2: "NO",
  },
  {
    common: "Nepal",
    official: "Federal Democratic Republic of Nepal",
    native: { official: "नेपाल संघीय लोकतान्त्रिक गणतन्त्र", common: "नेपाल" },
    cca2: "NP",
  },
  {
    common: "Nauru",
    official: "Republic of Nauru",
    native: { official: "Republic of Nauru", common: "Nauru" },
    cca2: "NR",
  },
  {
    common: "New Zealand",
    official: "New Zealand",
    native: { official: "New Zealand", common: "New Zealand" },
    cca2: "NZ",
  },
  {
    common: "Oman",
    official: "Sultanate of Oman",
    native: { official: "سلطنة عمان", common: "عمان" },
    cca2: "OM",
  },
  {
    common: "Pakistan",
    official: "Islamic Republic of Pakistan",
    native: { official: "Islamic Republic of Pakistan", common: "Pakistan" },
    cca2: "PK",
  },
  {
    common: "Panama",
    official: "Republic of Panama",
    native: { official: "República de Panamá", common: "Panamá" },
    cca2: "PA",
  },
  {
    common: "Pitcairn Islands",
    official: "Pitcairn Group of Islands",
    native: {
      official: "Pitcairn Group of Islands",
      common: "Pitcairn Islands",
    },
    cca2: "PN",
  },
  {
    common: "Peru",
    official: "Republic of Peru",
    native: { official: "Piruw Suyu", common: "Piruw" },
    cca2: "PE",
  },
  {
    common: "Philippines",
    official: "Republic of the Philippines",
    native: { official: "Republic of the Philippines", common: "Philippines" },
    cca2: "PH",
  },
  {
    common: "Palau",
    official: "Republic of Palau",
    native: { official: "Republic of Palau", common: "Palau" },
    cca2: "PW",
  },
  {
    common: "Papua New Guinea",
    official: "Independent State of Papua New Guinea",
    native: {
      official: "Independent State of Papua New Guinea",
      common: "Papua New Guinea",
    },
    cca2: "PG",
  },
  {
    common: "Poland",
    official: "Republic of Poland",
    native: { official: "Rzeczpospolita Polska", common: "Polska" },
    cca2: "PL",
  },
  {
    common: "Puerto Rico",
    official: "Commonwealth of Puerto Rico",
    native: { official: "Commonwealth of Puerto Rico", common: "Puerto Rico" },
    cca2: "PR",
  },
  {
    common: "North Korea",
    official: "Democratic People's Republic of Korea",
    native: { official: "조선민주주의인민공화국", common: "조선" },
    cca2: "KP",
  },
  {
    common: "Portugal",
    official: "Portuguese Republic",
    native: { official: "República português", common: "Portugal" },
    cca2: "PT",
  },
  {
    common: "Paraguay",
    official: "Republic of Paraguay",
    native: { official: "Tetã Paraguái", common: "Paraguái" },
    cca2: "PY",
  },
  {
    common: "Palestine",
    official: "State of Palestine",
    native: { official: "دولة فلسطين", common: "فلسطين" },
    cca2: "PS",
  },
  {
    common: "French Polynesia",
    official: "French Polynesia",
    native: { official: "Polynésie française", common: "Polynésie française" },
    cca2: "PF",
  },
  {
    common: "Qatar",
    official: "State of Qatar",
    native: { official: "دولة قطر", common: "قطر" },
    cca2: "QA",
  },
  {
    common: "Réunion",
    official: "Réunion Island",
    native: { official: "Ile de la Réunion", common: "La Réunion" },
    cca2: "RE",
  },
  {
    common: "Romania",
    official: "Romania",
    native: { official: "România", common: "România" },
    cca2: "RO",
  },
  {
    common: "Russia",
    official: "Russian Federation",
    native: { official: "Российская Федерация", common: "Россия" },
    cca2: "RU",
  },
  {
    common: "Rwanda",
    official: "Republic of Rwanda",
    native: { official: "Republic of Rwanda", common: "Rwanda" },
    cca2: "RW",
  },
  {
    common: "Saudi Arabia",
    official: "Kingdom of Saudi Arabia",
    native: {
      official: "المملكة العربية السعودية",
      common: "العربية السعودية",
    },
    cca2: "SA",
  },
  {
    common: "Sudan",
    official: "Republic of the Sudan",
    native: { official: "جمهورية السودان", common: "السودان" },
    cca2: "SD",
  },
  {
    common: "Senegal",
    official: "Republic of Senegal",
    native: { official: "République du Sénégal", common: "Sénégal" },
    cca2: "SN",
  },
  {
    common: "Singapore",
    official: "Republic of Singapore",
    native: { official: "新加坡共和国", common: "新加坡" },
    cca2: "SG",
  },
  {
    common: "South Georgia",
    official: "South Georgia and the South Sandwich Islands",
    native: {
      official: "South Georgia and the South Sandwich Islands",
      common: "South Georgia",
    },
    cca2: "GS",
  },
  {
    common: "Svalbard and Jan Mayen",
    official: "Svalbard og Jan Mayen",
    native: {
      official: "Svalbard og Jan Mayen",
      common: "Svalbard og Jan Mayen",
    },
    cca2: "SJ",
  },
  {
    common: "Solomon Islands",
    official: "Solomon Islands",
    native: { official: "Solomon Islands", common: "Solomon Islands" },
    cca2: "SB",
  },
  {
    common: "Sierra Leone",
    official: "Republic of Sierra Leone",
    native: { official: "Republic of Sierra Leone", common: "Sierra Leone" },
    cca2: "SL",
  },
  {
    common: "El Salvador",
    official: "Republic of El Salvador",
    native: { official: "República de El Salvador", common: "El Salvador" },
    cca2: "SV",
  },
  {
    common: "San Marino",
    official: "Most Serene Republic of San Marino",
    native: {
      official: "Serenissima Repubblica di San Marino",
      common: "San Marino",
    },
    cca2: "SM",
  },
  {
    common: "Somalia",
    official: "Federal Republic of Somalia",
    native: { official: "جمهورية الصومال‎‎", common: "الصومال‎‎" },
    cca2: "SO",
  },
  {
    common: "Saint Pierre and Miquelon",
    official: "Saint Pierre and Miquelon",
    native: {
      official: "Collectivité territoriale de Saint-Pierre-et-Miquelon",
      common: "Saint-Pierre-et-Miquelon",
    },
    cca2: "PM",
  },
  {
    common: "Serbia",
    official: "Republic of Serbia",
    native: { official: "Република Србија", common: "Србија" },
    cca2: "RS",
  },
  {
    common: "South Sudan",
    official: "Republic of South Sudan",
    native: { official: "Republic of South Sudan", common: "South Sudan" },
    cca2: "SS",
  },
  {
    common: "São Tomé and Príncipe",
    official: "Democratic Republic of São Tomé and Príncipe",
    native: {
      official: "República Democrática do São Tomé e Príncipe",
      common: "São Tomé e Príncipe",
    },
    cca2: "ST",
  },
  {
    common: "Suriname",
    official: "Republic of Suriname",
    native: { official: "Republiek Suriname", common: "Suriname" },
    cca2: "SR",
  },
  {
    common: "Slovakia",
    official: "Slovak Republic",
    native: { official: "Slovenská republika", common: "Slovensko" },
    cca2: "SK",
  },
  {
    common: "Slovenia",
    official: "Republic of Slovenia",
    native: { official: "Republika Slovenija", common: "Slovenija" },
    cca2: "SI",
  },
  {
    common: "Sweden",
    official: "Kingdom of Sweden",
    native: { official: "Konungariket Sverige", common: "Sverige" },
    cca2: "SE",
  },
  {
    common: "Eswatini",
    official: "Kingdom of Eswatini",
    native: { official: "Kingdom of Eswatini", common: "Eswatini" },
    cca2: "SZ",
  },
  {
    common: "Sint Maarten",
    official: "Sint Maarten",
    native: { official: "Sint Maarten", common: "Sint Maarten" },
    cca2: "SX",
  },
  {
    common: "Seychelles",
    official: "Republic of Seychelles",
    native: { official: "Repiblik Sesel", common: "Sesel" },
    cca2: "SC",
  },
  {
    common: "Syria",
    official: "Syrian Arab Republic",
    native: { official: "الجمهورية العربية السورية", common: "سوريا" },
    cca2: "SY",
  },
  {
    common: "Turks and Caicos Islands",
    official: "Turks and Caicos Islands",
    native: {
      official: "Turks and Caicos Islands",
      common: "Turks and Caicos Islands",
    },
    cca2: "TC",
  },
  {
    common: "Chad",
    official: "Republic of Chad",
    native: { official: "جمهورية تشاد", common: "تشاد‎" },
    cca2: "TD",
  },
  {
    common: "Togo",
    official: "Togolese Republic",
    native: { official: "République togolaise", common: "Togo" },
    cca2: "TG",
  },
  {
    common: "Thailand",
    official: "Kingdom of Thailand",
    native: { official: "ราชอาณาจักรไทย", common: "ประเทศไทย" },
    cca2: "TH",
  },
  {
    common: "Tajikistan",
    official: "Republic of Tajikistan",
    native: { official: "Республика Таджикистан", common: "Таджикистан" },
    cca2: "TJ",
  },
  {
    common: "Tokelau",
    official: "Tokelau",
    native: { official: "Tokelau", common: "Tokelau" },
    cca2: "TK",
  },
  {
    common: "Turkmenistan",
    official: "Turkmenistan",
    native: { official: "Туркменистан", common: "Туркмения" },
    cca2: "TM",
  },
  {
    common: "Timor-Leste",
    official: "Democratic Republic of Timor-Leste",
    native: {
      official: "República Democrática de Timor-Leste",
      common: "Timor-Leste",
    },
    cca2: "TL",
  },
  {
    common: "Tonga",
    official: "Kingdom of Tonga",
    native: { official: "Kingdom of Tonga", common: "Tonga" },
    cca2: "TO",
  },
  {
    common: "Trinidad and Tobago",
    official: "Republic of Trinidad and Tobago",
    native: {
      official: "Republic of Trinidad and Tobago",
      common: "Trinidad and Tobago",
    },
    cca2: "TT",
  },
  {
    common: "Tunisia",
    official: "Tunisian Republic",
    native: { official: "الجمهورية التونسية", common: "تونس" },
    cca2: "TN",
  },
  {
    common: "Turkey",
    official: "Republic of Turkey",
    native: { official: "Türkiye Cumhuriyeti", common: "Türkiye" },
    cca2: "TR",
  },
  {
    common: "Tuvalu",
    official: "Tuvalu",
    native: { official: "Tuvalu", common: "Tuvalu" },
    cca2: "TV",
  },
  {
    common: "Taiwan",
    official: "Republic of China (Taiwan)",
    native: { official: "中華民國", common: "台灣" },
    cca2: "TW",
  },
  {
    common: "Tanzania",
    official: "United Republic of Tanzania",
    native: { official: "United Republic of Tanzania", common: "Tanzania" },
    cca2: "TZ",
  },
  {
    common: "Uganda",
    official: "Republic of Uganda",
    native: { official: "Republic of Uganda", common: "Uganda" },
    cca2: "UG",
  },
  {
    common: "Ukraine",
    official: "Ukraine",
    native: { official: "Україна", common: "Україна" },
    cca2: "UA",
  },
  {
    common: "United States Minor Outlying Islands",
    official: "United States Minor Outlying Islands",
    native: {
      official: "United States Minor Outlying Islands",
      common: "United States Minor Outlying Islands",
    },
    cca2: "UM",
  },
  {
    common: "Uruguay",
    official: "Oriental Republic of Uruguay",
    native: { official: "República Oriental del Uruguay", common: "Uruguay" },
    cca2: "UY",
  },
  {
    common: "United States",
    official: "United States of America",
    native: { official: "United States of America", common: "United States" },
    cca2: "US",
  },
  {
    common: "Uzbekistan",
    official: "Republic of Uzbekistan",
    native: { official: "Республика Узбекистан", common: "Узбекистан" },
    cca2: "UZ",
  },
  {
    common: "Vatican City",
    official: "Vatican City State",
    native: { official: "Stato della Città del Vaticano", common: "Vaticano" },
    cca2: "VA",
  },
  {
    common: "Saint Vincent and the Grenadines",
    official: "Saint Vincent and the Grenadines",
    native: {
      official: "Saint Vincent and the Grenadines",
      common: "Saint Vincent and the Grenadines",
    },
    cca2: "VC",
  },
  {
    common: "Venezuela",
    official: "Bolivarian Republic of Venezuela",
    native: {
      official: "República Bolivariana de Venezuela",
      common: "Venezuela",
    },
    cca2: "VE",
  },
  {
    common: "British Virgin Islands",
    official: "Virgin Islands",
    native: { official: "Virgin Islands", common: "British Virgin Islands" },
    cca2: "VG",
  },
  {
    common: "United States Virgin Islands",
    official: "Virgin Islands of the United States",
    native: {
      official: "Virgin Islands of the United States",
      common: "United States Virgin Islands",
    },
    cca2: "VI",
  },
  {
    common: "Vietnam",
    official: "Socialist Republic of Vietnam",
    native: {
      official: "Cộng hòa xã hội chủ nghĩa Việt Nam",
      common: "Việt Nam",
    },
    cca2: "VN",
  },
  {
    common: "Vanuatu",
    official: "Republic of Vanuatu",
    native: { official: "Ripablik blong Vanuatu", common: "Vanuatu" },
    cca2: "VU",
  },
  {
    common: "Wallis and Futuna",
    official: "Territory of the Wallis and Futuna Islands",
    native: {
      official: "Territoire des îles Wallis et Futuna",
      common: "Wallis et Futuna",
    },
    cca2: "WF",
  },
  {
    common: "Samoa",
    official: "Independent State of Samoa",
    native: { official: "Independent State of Samoa", common: "Samoa" },
    cca2: "WS",
  },
  {
    common: "Yemen",
    official: "Republic of Yemen",
    native: { official: "الجمهورية اليمنية", common: "اليَمَن" },
    cca2: "YE",
  },
  {
    common: "South Africa",
    official: "Republic of South Africa",
    native: { official: "Republiek van Suid-Afrika", common: "South Africa" },
    cca2: "ZA",
  },
  {
    common: "Zambia",
    official: "Republic of Zambia",
    native: { official: "Republic of Zambia", common: "Zambia" },
    cca2: "ZM",
  },
  {
    common: "Zimbabwe",
    official: "Republic of Zimbabwe",
    native: { official: "Republic of Zimbabwe", common: "Zimbabwe" },
    cca2: "ZW",
  },
];

export default countries;
